extends Object

const _ENTITY = 0
const _GUI = 1
const _TILE = 95
const _TILE_LOCATION = 96
const _TILE_SPRITE = 97


const STATE_PLAYERTURN = 2
const STATE_AITURN = 3	
const STATE_ATTACK = 4	
const STATE_DEFEND = 5	
const STATE_ITEM = 6	
const STATE_SKILL = 7
const STATE_MAGIC = 8	
const STATE_ENDTURN = 9
const STATE_UNITSELECTED = 94

const STATE = {
	STATE_PLAYERTURN : "PlayerTurn",
	STATE_AITURN  : "AITurn",	
 	STATE_ATTACK  : "Attack",	
 	STATE_DEFEND : "Defend",	
	STATE_ITEM 	: "Item",
 	STATE_SKILL : "Skill",
 	STATE_MAGIC : "Magic",	
 	STATE_ENDTURN : "EndTurn",
	STATE_UNITSELECTED : "UnitSelected"
}

const JOB_SQUIRE = 10
const JOB_ENGINEER = 11
const JOB_ACOLYTE = 12
const JOB_ROGUE = 13
const JOB_CONJURER = 14

const JOB = {
	JOB_SQUIRE : "squire",
	JOB_ENGINEER : "engineer",
	JOB_ACOLYTE : "acolyte",
	JOB_ROGUE : "rogue",
	JOB_CONJURER : "conjurer"
}


const JOB_TYPE = 15
const JOB_DESCRIPTION = 16
const JOB_LEVELREQ = 17
const JOB_DAMAGE = 18
const JOB_TARGET_TYPE = 19
const JOB_PRIMARYSTAT = 20
const JOB_COOLDOWN = 21
const JOB_DOT = 22
const JOB_HEAL = 23
const JOB_DAMAGE_TAKEN = 24
const JOB_DAMAGE_ABSORB = 25
const JOB_INCOMING_DAMAGE = 26
const JOB_MANA = 90

const JOB_DAMAGE_REDUCTION = 27
const JOB_DAMAGE_ADDITION = 28

const JOB_MAINHAND = 29
const JOB_OFFHAND = 30
const JOB_ARMOR = 31

const JOB_STAT_REDUCTION = 32
const JOB_STAT_ADDITION = 33
const JOB_VALUE = 34

const JOB_WEAPON_DAGGER = 35
const JOB_WEAPON_STAFF = 36
const JOB_WEAPON_SYMBOL = 37
const JOB_WEAPON_SWORD = 38
const JOB_WEAPON_PISTOL = 39

const JOB_ARMOR_CLOTH = 40
const JOB_ARMOR_LEATHER = 41
const JOB_ARMOR_CHAINMAIL = 42

const JOB_TARGET_TYPE_SINGLE = 43
const JOB_TARGET_TYPE_SELF = 44

const JOB_DOT_DURATION = 45
const JOB_DOT_PERTURN = 46
const JOB_DOT_EFFECT = 47

const JOB_DOT_EFFECT_STEALTH = 48
const JOB_DOT_EFFECT_BLEED = 49
const JOB_DOT_EFFECT_POISON = 50

const JOB_TYPE_PHYSICAL = 51
const JOB_TYPE_NATURE = 52
const JOB_TYPE_LIGHT = 53
const JOB_TYPE_DEFENSIVE = 54
const JOB_TYPE_EMPOWER = 55
const JOB_TYPE_FIRE = 56
const JOB_TYPE_WATER = 57
const JOB_TYPE_EARTH = 58
const JOB_TYPE_AIR = 59



const ENTITY_ID = 60
const ENTITY_NAME = 61

const ENTITY_HITPOINTS = 62
const ENTITY_HITPOINTS_CURRENT = 63
const ENTITY_HITPOINTS_TOTAL = 64

const ENTITY_MANA = 65
const ENTITY_MANA_CURRENT = 66
const ENTITY_MANA_TOTAL = 67

const ENTITY_SPEED = 68
const ENTITY_INTELLECT = 69
const ENTITY_DEXTERITY = 70
const ENTITY_STRENGTH = 71

const ENTITY_TYPE = 72
const ENTITY_TYPE_NONE = 73
const ENTITY_TYPE_FRIENDLY = 74
const ENTITY_TYPE_ENEMY = 75

const ENTITY_ACTION_POINTS = 76
const ENTITY_JOB = 77
const ENTITY_DEBUFF = 78
const ENTITY_BUFF = 79

const ENTITY_LEVEL = 80
const ENTITY_EXP = 81
const ENTITY_EXP_CURRENT = 82
const ENTITY_EXP_TOTAL = 83 

const ENTITY_MOVE = 90
const ENTITY_HAS_MOVED = 91
const ENTITY_MOVE_RANGE = 92
const ENTITY_ENDTURN = 93

const ACTIONMENU_NONE = 84 
const ACTIONMENU_ATTACK = 85 
const ACTIONMENU_DEFEND = 86 
const ACTIONMENU_ITEM = 87 
const ACTIONMENU_SKILL = 88
const ACTIONMENU_MAGIC = 89
	


#at 97
